using UnityEngine;
using System.Collections;
using UnityEngine.UI;

public class AnimateText3 : MonoBehaviour
{
	public float letterPause = 0.2f;
	string message;
	private float timer;
	
	void Start ()
	{
		message = GetComponent<Text> ().text;
		GetComponent<Text> ().text = "";
	}
	
	void Update()
	{
		if(GetComponent<Text>().text == message)
		{
			timer += Time.deltaTime;
			if(timer >= 1)
			{
				Application.LoadLevel("MainScene");
			}
		}
	}
	
	public void Wait()
	{
		StartCoroutine (TypeText3());
	}
	
	IEnumerator TypeText3 ()
	{
		foreach (char letter in message.ToCharArray())
		{
			GetComponent<Text>().text += letter;
			yield return 0;
			yield return new WaitForSeconds (letterPause);
		}
	}
}
